<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-A4I74VVH" failures="1" tests="8" name="Test" time="7.483" errors="0" timestamp="2024-05-08T09:41:36 IST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="2.634"/>
  <testcase classname="api.test.StoreTests" name="getOrderById" time="2.859">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.StoreTests.getOrderById(StoreTests.java:62)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- getOrderById -->
  <testcase classname="api.test.StoreTests" name="testGetPetInventory" time="1.274"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.318"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="1.189"/>
  <testcase classname="api.test.StoreTests" name="createPlaceOrder" time="1.25"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.318"/>
  <testcase classname="api.test.StoreTests" name="deleteOrderById" time="1.327"/>
</testsuite> <!-- Test -->
